### ISSUE TITLE
gtm_head.js missing

### ISSUE THREAD

**Issue by dnieuw** [AlienDeg/shinyexplorer#1]
I've cloned and tried out your app, but I'm unable to run it because the javascript file gtm_head.js is not included in the repo. Where can I obtain this file?

**Comment by bowerth** [comment]
you can simply remove the header parameter, e.g. `navbarPage(# header = tags$head(includeScript("gtm_head.js"))`. The repo is missing more files, e.g. all the geom_ PNGs

**Comment by AlienDeg** [comment]
@dnieuw @bowerth sorry guys. I'm quite new to github, and did everything wrong. However I updated repository and it should work now. Let me know. Thanks for feedback!

**Comment by bowerth** [comment]
Looking good, much appreciated!
Guess this can be closed @dnieuw
